### ISSUE TITLE
Test for private key limits

### ISSUE THREAD

**Issue by mvasilkov** [mvasilkov/OpenBalkans#11]
https://crypto.stackexchange.com/a/30272

Upd: there's an implicit modulo operation, so the upper boundary doesn't matter much.

**Comment by romankoblov** [comment]
They all valid if library doesn’t explicitly forces this limit. But there is not much reason to do that.

**Comment by mvasilkov** [comment]
Ah correct we've discussed this already. I've managed to forget lol.
