### ISSUE TITLE
Check the base58 implementations

### ISSUE THREAD

**Issue by mvasilkov** [mvasilkov/OpenBalkans#13]
JS: https://www.npmjs.com/package/base-x
Python: https://github.com/keis/base58

- Check that buffers with leading 00 work the same
- Is this even fine

**Comment by romankoblov** [comment]
https://github.com/paulmillr/base58-encode.js is small and without dependencies

**Comment by mvasilkov** [comment]
@romankoblov nice! We need `base58.decode()` too tho.

Everything looks compatible between JS and Python, too. (I had to check.)
